### PR TITLE
Fix error with broken mutate-rows test

### LINKED ISSUE #51: Releasing 0.12.0 Stalled
0.12.0 was not released 16 days ago due to some error: https://circleci.com/gh/googleapis/nodejs-bigtable/1109

I'm trying to get the release through now, but we're stalled on a new error.

@kolodny could you please take a look?

https://circleci.com/gh/googleapis/nodejs-bigtable/1408:

```
1) Bigtable/Table
       mutate()
         valid mutation:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules/lolex/src/lolex-src.js:671:15)
      at Context.done (system-test/mutate-rows.js:132:15)

  2) Bigtable/Table
       mutate()
         retries the failed mutations:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules/lolex/src/lolex-src.js:671:15)
      at Context.done (system-test/mutate-rows.js:132:15)

  3) Bigtable/Table
       mutate()
         has a `PartialFailureError` error when an entry fails after the retries:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules/lolex/src/lolex-src.js:671:15)
      at Context.done (system-test/mutate-rows.js:132:15)

  4) Bigtable/Table
       mutate()
         does not retry unretryable mutations:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules/lolex/src/lolex-src.js:671:15)
      at Context.done (system-test/mutate-rows.js:132:15)

  5) Bigtable/Table
       mutate()
         considers network errors towards the retry count:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules/lolex/src/lolex-src.js:671:15)
      at Context.done (system-test/mutate-rows.js:132:15)

  6) Bigtable/Table
       createReadStream
         simple read:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  7) Bigtable/Table
       createReadStream
         retries a failed read:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  8) Bigtable/Table
       createReadStream
         resets the retry counter after a successful read:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  9) Bigtable/Table
       createReadStream
         moves the start point of a range being consumed:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  10) Bigtable/Table
       createReadStream
         removes ranges already consumed:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  11) Bigtable/Table
       createReadStream
         removes keys already read:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  12) Bigtable/Table
       createReadStream
         adjust the limit based on the number of rows read:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  13) Bigtable/Table
       createReadStream
         does the previous 5 things in one giant test case:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)
```

### PR DESCRIPTION
**Pull request by kolodny**
Fixes #51 

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
~[ ] Appropriate docs were updated (if necessary)~

### CODE REVIEW

**Comment by stephenplusplus** [comment]
It looks like some new errors emerged: https://circleci.com/gh/googleapis/nodejs-bigtable/1578?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by kolodny** [comment]
Weird this doesn't happen for me, can you try to rebuild without cache https://circleci.com/docs/1.0/how-cache-works/#clearing-cache

**Comment by stephenplusplus** [comment]
I can't reproduce locally, either. I pushed a commit to revert your change, just to see if Circle is unhappy about everything, or just your commit.

**Comment by stephenplusplus** [comment]
Looks like it is indeed the commit, as Circle is green.

**Comment by stephenplusplus** [comment]
Pushed the original commit back with a re-revert.

**Comment by stephenplusplus** [comment]
Looks like it's happy now with your original changes. Merge time!

**Pull request merged**
