### PR TITLE
Implement read-rows-acceptance-test pr1

### PR DESCRIPTION
**Pull request by ajaaym**
Issue #<10> Adding test case json file and chunk parser 

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Will there be more coming to this PR? I might be missing it, but it doesn't seem like any new tests are being run.

**Comment by ajaaym** [comment]
Yes there will be one more pr which would run the testcase.

**Comment by stephenplusplus** [comment]
Is it possible to put all of the changes into this PR?

**Comment by ajaaym** [comment]
Yes. Will update this pr with testcase change.

**Comment by sduskis** [comment]
You can also see PR #12 for the full test and history as to why I asked for #12 to be broken down.

**Comment by stephenplusplus** [comment]
Ah, sorry that I missed that. My initial thought is not to have code in the repo that we aren't using, but it's not a big deal either way.

Regarding this PR, it looks like the [`lint` task failed](https://circleci.com/gh/googleapis/nodejs-bigtable/195?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). @ajaaym you sould be able to run `npm run prettier` and have the formatting done automatically.

**Pull request closed without merging**
