### PR TITLE
Release @google-cloud/bigtable v0.16.0

### PR DESCRIPTION
**Pull request by sduskis**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
What's up with the failing system tests?

**Comment by sduskis** [comment]
@muraliQlogic, can you please take a look?

**Comment by muraliQlogic** [comment]
@sduskis : The issue is because of createPrefixRange_ that we made public. I am analysing it further and will fix asap.

**Comment by muraliQlogic** [comment]
@sduskis : Fix is pushed via https://github.com/googleapis/nodejs-bigtable/pull/322

**Comment by sduskis** [comment]
@googleapis/yoshi-nodejs, this PR is up to date with all issues.  Can I please get a review?

**Comment by JustinBeckwith** [comment]
Release is at https://github.com/googleapis/nodejs-bigtable/releases/tag/v0.16.0

**Comment by JustinBeckwith** [comment]
I tried to do a release, but the system-tests failed. I don't seem to have permissions to restart the job in CircleCI.  @sduskis can you try re-running this job? 
https://circleci.com/gh/googleapis/nodejs-bigtable/9718

**Comment by rarkins** [comment]
@JustinBeckwith I got a notification because of the rollback PR #324 for `@google-cloud/bigtable`. Version 0.16.0 never made it to npmjs so this package.json update was kind of invalid.

**Pull request merged**
