### PR TITLE
fix(types): Include TypeScript types with module

### LINKED ISSUE #526: Emit typescript types on build
**Is your feature request related to a problem? Please describe.**
While using this library there is absolutely 0 typing information available on import. There is a constant need to have the docs open or div into the source code itself to be able to use this library. 

Most of the code is written in typescript why wouldn't types be emitted?

 **Describe the solution you'd like**
Typescript definition files should be emitted on build.
 **Describe alternatives you've considered**
I suppose I could generate my own and commit them to DT but I feel that wouldn't be the right approach.

### PR DESCRIPTION
**Pull request by csidell-earny**
Fixes #526

- [ X ] Tests and linter pass
- [ X ] Code coverage does not decrease (if any source code was changed)
- [ X ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by csidell-earny** [comment]
@googlebot I signed it!

**Comment by csidell-earny** [comment]
@JustinBeckwith I wouldn't know what it is upstream, I assume it's the same filename?

**Comment by JustinBeckwith** [comment]
It should look exactly like the line I pointed to above :)

**Comment by csidell-earny** [comment]
Well in that case that change has been made!

**Comment by csidell-earny** [comment]
Should be ready to merge, undid the type fixes for some of the exists() calls as to not have this do more than the original PR title. @JustinBeckwith

**Pull request merged**
