### PR TITLE
Fix for Issue#343

### LINKED ISSUE #343: Empty column qualifiers should not be rejected
Relevant code is here for reads: https://github.com/googleapis/nodejs-bigtable/blob/13e3d769/src/chunktransformer.js#L251

It's completely valid to use a column like "fam:" which has no qualifier

### PR DESCRIPTION
**Pull request by muraliQlogic**
Fixes #343  

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by sduskis** [comment]
@muraliQlogic: The requirement is to have a check that requires a family with a qualifier.  The qualifier could be the empty string.  This PR doesn't look right.

**Comment by sduskis** [comment]
fam":"" is fine, but "fam":[null] is not ok. I believe the if statement checks for "fam":[null] rather than "fam":"". We should add a unit test to confirm that.  @muraliQlogic, can you please change the the chunktransformer.js test for those requirements?

**Comment by muraliQlogic** [comment]
@sduskis : I modified if condition to check for null or undefined qualifier.

**Comment by sduskis** [comment]
@muraliQlogic: Does `ChunkTransformer. validateNewRow` also need the check for null or undefined?

**Pull request merged**
