### PR TITLE
Updating the Readme: Node is now beta

### PR DESCRIPTION
**Pull request by sduskis**
This works towards issue #224.

The client is ready for Beta.  This PR updates the readme.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
There's also a badge at the top of the README that needs to be changed to `beta` :)

**Comment by sduskis** [comment]
@JustinBeckwith: thanks!  I updated the badge

**Comment by stephenplusplus** [comment]
I caught it here as well: https://github.com/googleapis/nodejs-bigtable/blob/443ba9b2bf33de7de6cf49b3a1feb231eda88375/.cloud-repo-tools.json

**Comment by sduskis** [comment]
Thanks for finding All The Places.  This will likely be one of my most satisfying "Squash and merge" presses.

**Pull request merged**
