### PR TITLE
revert!: remove failedLocation from getInstancesCallback/Response

### PR DESCRIPTION
**Pull request by AVaksman**
Reverting back as per https://github.com/googleapis/nodejs-bigtable/pull/731#discussion_r450451297

- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Just confirming, this is breaking from master, but not the last release, right?

**Comment by AVaksman** [comment]
> Just confirming, this is breaking from master, but not the last release, right?

Correct

**Review by stephenplusplus — DISMISSED** [review]
There are some example blocks that need to be updated.

**Comment by AVaksman** [comment]
> There are some example blocks that need to be updated.

Done, thanks!

**Comment by AVaksman** [comment]
> > Just confirming, this is breaking from master, but not the last release, right?
> 
> Correct

Now it is a breaking change from the last release 😮 #743

**Review by crwilcox — APPROVED** [review]

**Comment by crwilcox** [comment]
FYI @kolea2

**Review by kolea2 — APPROVED** [review]

**Pull request merged**
