### PR TITLE
chore(testproxy): read row should return a single row

### PR DESCRIPTION
**Pull request by danieljbruce**
To get one of the specific test cases passing for readRow, we need a slight fix to the way returned data is parsed.

### CODE REVIEW

**Comment by ruyadorno** [comment]
it'd be nice for the commit message to mention that this is related to the test proxy and not the implementation itself 😊 maybe prepend `testproxy: ` to the title?

**Review by ruyadorno — COMMENTED** [review]
LGTM 👍

**Comment by danieljbruce** [comment]
> it'd be nice for the commit message to mention that this is related to the test proxy and not the implementation itself 😊 maybe prepend `testproxy: ` to the title?

Unfortunately for the conventional commits to pass we must prefix with a specific word. Probably `test:` in this case.

https://www.conventionalcommits.org/en/v1.0.0/

Maybe set to `test: testproxy: Slight change in data returned by readRow`?

**Comment by ruyadorno** [comment]
maybe we can use: `test(testproxy): read row should return a single row` so that it's also a bit more descriptive of the change

**Comment by ruyadorno** [comment]
for reference, I used `chore` in the commit I introduced the testproxy, ref: 0b3d996a667029cf2259dcc8f22d0dc537bf33f0

**Review by ruyadorno — APPROVED** [review]

**Pull request merged**
